rules:
  dangerous-triggers:
    ignore:
      - coverage.yaml:3:1
  unpinned-uses:
    config:
      policies:
        "*": ref-pin
  superfluous-actions:
    ignore:
      - publish-release.yaml:78:15
