name: Test-APIs

on:
  schedule:
    - cron: "12 12 12 * *" # run once a month on the 12th at 12:12

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-api:
    name: Test APIs
    if: github.repository == 'Diaoul/subliminal' && github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: install
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[test]"
      - name: remove cassettes
        run: |
          rm -rf tests/cassettes
      - name: run test
        run: |
          pytest
