name: Tag release

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      version:
        description: 'Release tag version.'
        type: string
        default: NONE
        required: true

permissions: {}

env:
  FORCE_COLOR: "1"

# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
jobs:
  # Always build & lint package.
  build-package:
    name: Build & verify package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: hynek/build-and-inspect-python-package@v2

  define-tag:
    name: Define tag
    # tag a release after a release PR was accepted
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ''
    steps:
      - if: github.event_name == 'workflow_dispatch'
        name: from workflow_dispatch
        env:
          RELEASE_VERSION: ${{ inputs.version }}
        run: TRUE
      - if: |
          github.repository == 'Diaoul/subliminal'
          && github.event_name == 'pull_request'
          && github.event.action == 'closed'
          && github.event.pull_request.merged == true
          && github.event.pull_request.head.repo.full_name == github.repository
          && contains(github.event.pull_request.labels.*.name, 'type/release')
          && startsWith(github.head_ref, 'releases/')
        name: from merged PR
        run: |
          echo "RELEASE_VERSION=${GITHUB_HEAD_REF#release-}" >> $GITHUB_ENV
      - run: echo "$RELEASE_VERSION"

    outputs:
      tag: $RELEASE_VERSION

  tag-and-release:
    name: Tag and publish a release draft
    needs: [define-tag, build-package]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    if: ${{ define-tag.outputs.tag != ''}}
    env:
      RELEASE_VERSION: ${{ define-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Tag the commit
        run: |
          echo Release version: $RELEASE_VERSION
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git tag --annotate --message="Release version $RELEASE_VERSION" $RELEASE_VERSION ${{ github.sha }}
          git push origin $RELEASE_VERSION

      - uses: ./.github/workflows/publish-release.yml
        # publish a release draft after pushing the release tag
        with:
          tag-name: $RELEASE_VERSION
